---
name: David
surname: Ubilava
position: "Associate Professor"
address: "School of Economics, University of Sydney"
www: davidubilava.com
email: "david.ubilava@sydney.edu.au"
twitter: DavidUbilava
date: "`r format(Sys.time(), '%B %Y')`"
output:
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Professional Summary

 * Applied economist; research in food and agricultural markets, climate, and conflict.
 * Associate Professor, School of Economics, University of Sydney.
 * Co-Editor-in-Chief, *Food Policy*; past Associate Editor, *American Journal of Agricultural Economics*.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Ph.D. Agricultural Economics", "2010", "Purdue University", "USA",
  "M.S. Agricultural Economics", "2006", "Purdue University", "USA",
  "B.S. Economics", "2003", "Georgia State Agrarian University", "Georgia"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Awards and Service

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  2025, "Award", "Quality of Research Discovery Award, Australasian Agricultural and Resource Economics Society",
  2024, "Award", "Research Collaboration Award, Faculty of Arts and Social Sciences",
  2017, "Award", "Faculty of Arts and Social Sciences Teaching Excellence Award"
) %>%
  brief_entries(
    Type,
    Year,
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```
